package be.tcuvelier.qdoctools.io.todocx;

public enum Level {
    ROOT_ARTICLE, ROOT_ARTICLE_INFO, ROOT_BOOK, ROOT_BOOK_INFO, PART, PART_INFO, CHAPTER, CHAPTER_INFO,
    SECTION, SECTION_INFO,
    TABLE,
    ITEMIZED_LIST, ORDERED_LIST, SEGMENTED_LIST, SEGMENTED_LIST_TITLE, VARIABLE_LIST,
    BLOCK_PREFORMATTED
}
